apiVersion: v1
kind: Service
metadata:
  name: xbank-harness-svc
  namespace: xbank-agentive
spec:
  selector:
    app: xbank-harness
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
